child and task state passing from api call
Lambda-School-Labs/Labs26-StorySquad-FE-TeamB pull request #50
Opened 2020-09-30 20:01 UTC by Schrese

# Description

Fixes #

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2020-10-01 16:32 UTC, SandraCoburn commented on src/state/reducers/taskReducer.js
> +        hasDrawn: action.payload.HasDrawn,
wouldn't you need to make a copy of state before modifying? 
return {...state, and then what you want to modify}

2020-10-06 18:04 UTC, bramirez96 requested changes
Let's keep the UploadDocs component modular! I've marked a few potential changes to help with this

2020-10-06 18:04 UTC, bramirez96 commented on src/state/reducers/taskReducer.js
> +        hasDrawn: action.payload.HasDrawn,
In this case it should be fine because every field is being set in the return statement!

2020-10-06 18:04 UTC, bramirez96 commented on src/components/common/UploadDocs.js
> +  const [maxLength, setMaxLength] = useState(1);
We can pass this in as a prop instead of using a state hook!

2020-10-06 18:04 UTC, bramirez96 commented on src/components/common/UploadDocs.js
> +  setHasDrawn,
We can pass a reference to a function instead of passing both functions in and conditionally calling them!

2020-10-06 18:05 UTC, Nick-Ohman submitted a review, later dismissed

2020-10-06 19:10 UTC, SandraCoburn approved these changes, later dismissed
That's a lot of code! Good job.

2020-10-06 22:41 UTC, SandraCoburn approved these changes
Thanks for fixing the tests!

2020-10-06 22:41 UTC, bramirez96 approved these changes
Nice work on all of this! I know it was a lot you CRUSH'D IT

2020-10-06 22:41 UTC, merged